---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - consumer_key is defined
      - consumer_secret is defined
      - access_token_key is defined
      - access_token_secret is defined
      - subs_uri is defined
      - subs_encoding is defined
      - video_uri is defined
      - output_uri is defined
      - text_color is defined
      - text_size is defined
      - text_font is defined
      - idle_period is defined

- name: Create the movie directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}/movies"
    state: directory
    mode: 0700

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    pull: true
    restart_policy: "always"
    memory: "200MB"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}movies:/movies"
    env:
      CONSUMER_KEY: "{{ consumer_key }}"
      CONSUMER_SECRET: "{{ consumer_secret }}"
      ACCESS_TOKEN_KEY: "{{ access_token_key }}"
      ACCESS_TOKEN_SECRET: "{{ access_token_secret }}"
      SUBS_URI: "{{ subs_uri }}"
      SUBS_ENCODING: "{{ subs_encoding }}"
      VIDEO_URI: "{{ video_uri }}"
      OUTPUT_URI: "{{ output_uri }}"
      TEXT_COLOR: "{{ text_color }}"
      TEXT_SIZE: "{{ text_size }}"
      TEXT_FONT: "{{ text_font }}"
      IDLE_PERIOD: "{{ idle_period }}"
      SENTRY_URL: "{{ sentry_url }}"
